language: shell
os: linux
arch: amd64

addons:
  apt:
    packages: mlton
  homebrew:
    packages: mlton

jobs:
  include:
  - os:   linux
    dist: bionic
    arch: amd64
    env:  CC=gcc    MLTON_COMPILE_ARGS="-codegen amd64"  REGRESSION=true
  - os:   linux
    dist: bionic
    arch: amd64
    env:  CC=gcc    MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false
  - os:   linux
    dist: bionic
    arch: amd64
    env:  CC=clang  MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false
  - os:   linux
    dist: bionic
    arch: amd64
    env:  CC=clang  MLTON_COMPILE_ARGS="-codegen llvm"   REGRESSION=false
  - os: osx
    osx_image: xcode12
    arch: amd64
    env:  CC=clang  MLTON_COMPILE_ARGS="-codegen amd64"  REGRESSION=false
  - os: osx
    osx_image: xcode12
    arch: amd64
    env:  CC=clang  MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false

script:
  - ./bin/travis-ci

notifications:
  email: false
