language: generic

dist: bionic
osx_image: xcode11

addons:
  apt:
    packages: mlton
  homebrew:
    packages: mlton

matrix:
  include:
  - os:   linux
    env:  CC=gcc    MLTON_COMPILE_ARGS="-codegen amd64"  REGRESSION=true
  - os:   linux
    env:  CC=gcc    MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false
  - os:   linux
    env:  CC=clang  MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false
  - os:   linux
    env:  CC=clang  MLTON_COMPILE_ARGS="-codegen llvm"   REGRESSION=false
  - os: osx
    env:  CC=clang  MLTON_COMPILE_ARGS="-codegen amd64"  REGRESSION=false
  - os: osx
    env:  CC=clang  MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false

script:
  - ./bin/travis-ci

notifications:
  email: false
